GET http://localhost:5002



###Login Route
POST  http://localhost:5002/auth/login 
content-type: application/json

{
  
  "email": "Laabidi.ryadh@esprit.tn",
  "password": "12345678"
  
}

####Register Route
POST  http://localhost:5002/auth/register
Content-Type: application/json

{
  
  "email": "Laabidi.zeineb@esprit.tn",
  "password": "12345678"
  
}

###Logout Route
   http://localhost:5002/auth/logout



   
   


